Chronos-EaaS/Chronos-Control

- api/v1/job.php
- config.template.php
- controllers/admin.php
- install.php
- libraries/vcs.php
- views/admin/main.php
Certain config variables are stored in the database now and can be removed from the config template
> Store certain settings in the database

- libraries/builder.php
> Escaping of rendered templates

- chronos.sql
- controllers/builder.php
- controllers/results.php
- core/plot.php
- core/util.php
- libraries/builder.php
- libraries/dba/models/Job.class.php
- libraries/dba/models/JobFactory.class.php
- libraries/dba/models/generator.php
- libraries/evaluation.php
- libraries/graphs/bar-plot/process.php
- libraries/graphs/line-plot-multi/process.php
- libraries/graphs/line-plot/process.php
- libraries/graphs/pie-plot/process.php
- libraries/results.php
- views/builder/create.php
Allows to define how many runs with the same configuration should be run which are then averaged for results.
Additionally some speed improvements were added.
> Multiple jobs with same configuration

- core/router.php
> Fixing forward error on session timeout

- api/v1/evaluation.php
- api/v1/experiment.php
- api/v1/job.php
- api/v1/project.php
- views/evaluation/detail.php
- views/experiment/detail.php
- views/job/detail.php
- views/project/detail.php
> Fix dismissable messages and provide helpful error messages

- controllers/project.php
- views/project/detail.php
- views/project/overview.php
Archived/own projects are correctly shown when using checkboxes
closes #37
> Fix selections for project overview

- core/define.php
- libraries/evaluation.php
- libraries/results.php
> Display single job result titles without run numbers

- controllers/project.php
- views/project/detail.php
> Add button to un-archive a project

- controllers/admin.php
- views/admin/system.php
- views/admin/systems.php
> Add logo upload for systems

- controllers/evaluation.php
- views/evaluation/detail.php
Mass actions on jobs can be applied on evaluations (abort all, re-schedule all)
closes #40
> Mass actions on jobs

- controllers/evaluation.php
- views/evaluation/detail.php
> Changed submission of re-schedule and abort all to POST

- controllers/project.php
> Fix missing listing of own projects

- libraries/elements/boolean/render.template.html
- libraries/elements/checkbox-selection/render.template.html
- libraries/elements/dropdown/render.template.html
- libraries/elements/integer/render.template.html
- libraries/elements/interval/render.template.html
- libraries/elements/percentage/build.template.html
- libraries/elements/percentage/config.json
- libraries/elements/percentage/render.template.html
- libraries/elements/ratio/render.template.html
- libraries/elements/string-list/render.template.html
- libraries/elements/string/render.template.html
- views/builder/create.php
- webroot/design/default/footer.php
- webroot/design/default/header.php
* added new element "percentage" allowing dependency from other values
* reworked other elements to have consistent style
closes #55
> Add new parameter type "percentage"

- views/admin/system.php
- views/project/detail.php
> Ask for confirmation when archiving projects or systems

- controllers/admin.php
- core/autoloader.php
- core/processexception.php
- core/view.php
- views/home/error.php
- views/home/error403.php
- views/home/error404.php
- views/home/handlingError.php
Added a new exception page to handle such soft errors with a more appropriate view
closes #28
> Disable archiving systems which are used in active projects

- core/util.php
> Fixing issue when rendering multi-line plot

- controllers/builder.php
- core/element.php
- core/util.php
- libraries/builder.php
- libraries/elements/boolean/render.template.html
- libraries/elements/checkbox-selection/copy.php
- libraries/elements/checkbox-selection/render.template.html
- libraries/elements/dropdown/render.template.html
- libraries/elements/integer/render.template.html
- libraries/elements/interval/copy.php
- libraries/elements/interval/render.template.html
- libraries/elements/percentage/copy.php
- libraries/elements/percentage/render.template.html
- libraries/elements/ratio/copy.php
- libraries/elements/ratio/render.template.html
- libraries/elements/string-list/render.template.html
- libraries/elements/string/render.template.html
- views/builder/create.php
- views/project/detail.php
> Allowing to create experiments based on others

- core/util.php
- libraries/dba/AbstractModelFactory.class.php
> Avoid loading too much data in timeline queries

- api/ui/results.php
- chronos.sql
- controllers/admin.php
- controllers/experiment.php
- controllers/results.php
- core/system.php
- core/util.php
- libraries/dba/models/Experiment.class.php
- libraries/dba/models/ExperimentFactory.class.php
- libraries/dba/models/ExperimentView.class.php
- libraries/dba/models/ExperimentViewFactory.class.php
- libraries/dba/models/generator.php
- libraries/event.php
- libraries/results.php
- views/admin/system.php
- views/builder/build.php
- views/experiment/detail.php
- views/results/build.php
> Allowing multiple result definitions, either system-wide or per experiment

- controllers/admin.php
- controllers/builder.php
- libraries/elements/ratio/process.php
- views/admin/system.php
- views/builder/create.php
closes #111 
Also fixes unchecked number of parameter strings for ratio element.
> Fixed missing warm up phase checkbox for experiments

- libraries/elements/integer/build.template.html
- libraries/elements/integer/render.template.html
- libraries/elements/interval/build.template.html
- libraries/elements/interval/process.php
- libraries/elements/interval/render.template.html
- libraries/elements/percentage-interval/build.template.html
- libraries/elements/percentage-interval/render.template.html
> Fix displaying of zero values on parameter elements

- views/evaluation/detail.php
- views/project/detail.php
> Allow changing the name with empty description for Evaluations and Projects

- controllers/job.php
- views/job/detail.php
> Added buttons to navigate directly between jobs of an evaluation

- views/job/detail.php
- webroot/assets/ansi_js/asset.php
- webroot/assets/ansi_js/js/ansi_up.js
> Support ANSI colors in job log output

- controllers/project.php
- views/project/detail.php
> Allow archiving of experiments if no evaluation is running

- controllers/experiment.php
- views/experiment/detail.php
> Allow archiving of evaluations if they are not running

- chronos.sql
- controllers/evaluation.php
- controllers/project.php
- libraries/dba/models/Evaluation.class.php
- libraries/dba/models/EvaluationFactory.class.php
- libraries/dba/models/EvaluationView.class.php
- libraries/dba/models/EvaluationViewFactory.class.php
- libraries/dba/models/generator.php
- views/evaluation/detail.php
- views/experiment/detail.php
- views/project/detail.php
> Evaluations can be starred and viewed in project overview

- views/builder/create.php
> Fix broken copy of experiment settings for warmUp phase

- libraries/elements/interval/copy.php
- libraries/elements/interval/render.template.html
> Fix checking for copy values on the interval element

- controllers/evaluation.php
> Changing experiment lookup to using view in order to include project memberships

- views/experiment/detail.php
- views/project/detail.php
> Adding min-width for columns of experiments and evaluations to avoid wrapping

- libraries/graphs/bar-plot/process.php
Instead of just showing the job number, the changing parameters are listed.
> Also show the changing parameters on Box Plots

- core/util.php
- libraries/graphs/line-plot/process.php
This PR adds support for rendering arrays in line plots of job-specific results
> Enhance line plots for job-specific results

- controllers/project.php
- views/project/detail.php
This PR fixes the broken functionality, which allows to add other members to a specific project.
> Fix adding members to projects

- .github/workflows/lint.yaml
Run basic syntax checks on PHP files with `php -l`.
> Add workflow to run `php -l` on PHP files
